export const TOKEN_GTDEL = 'w3XsSy8bf7lJQqbYX1j5r9Tg7osUZRWj';

export const URL_COMPANY = {
  GTDEL: 'https://capi.gtdel.com/1.0/order/calculate',
  DELLIN: 'https://www.dellin.ru/api/calculation/v1/main_page/priority_price?derival_point_code=',
  BAIKAL: 'https://www.baikalsr.ru/json/alter_calc.php?fix_delivery=1&',
  NRG: 'https://api2.nrg-tk.ru/v2/price',
  JDE: 'https://api.jde.ru/vD/calculator/price',
  PONY_EXPRESS: 'https://www.ponyexpress.ru/local/ajax/tariff.php',
  EXPRESS_AUTO: 'http://expressauto.ru/ajax/',
  SHIPTOR: 'https://api.shiptor.ru/public/v1',
};

export const OTHER_URL_COMPANY = {
  GET_CITIES_NRG: 'https://api2.nrg-tk.ru/v2/cities',
  BAIKAL_ID_SITY: 'https://request.baikalsr.ru/json/fias_cities.php?text=',
  DELLIN_ID_SITY: 'https://www.dellin.ru/api/cities/search.json?q=',
  GTDEL_GET_SITY: 'https://capi.gtdel.com/1.0/tdd/search/by-name',
  EXPRESS_AUTO: 'http://expressauto.ru/ajax/',
  SHIPTOR_KLADR: 'https://api.shiptor.ru/public/v1',
};

export const TRANSPORT_COMPANIES_LIST = [
  {
    name: 'Деловые линии',
    label: 'dellin',
    site: 'dellin.ru',
    logoUrl: 'https://pr.dellin.ru/wp-content/uploads/2019/02/Lodo_DL_1_RGB.png',
    price: 1000.0,
    deliveryTerm: 2,
    calculateUrl: 'https://www.dellin.ru/requests/',
  },
  {
    name: 'ПЭК',
    label: 'pec',
    site: 'pecom.ru',
    logoUrl: 'https://pecom.ru/local/vue-cli-build/images/logo.svg',
    price: 1000.0,
    deliveryTerm: 2,
    calculateUrl: 'https://pecom.ru/services-are/shipping-request/',
  },
  {
    name: 'Энергия',
    label: 'nrg',
    site: 'nrg-tk.ru',
    logoUrl: 'https://krymskie-svechi.ru/images/dostavka-energiya.png',
    price: 2000.0,
    deliveryTerm: 2,
    calculateUrl: 'https://nrg-tk.ru/client/calculator/',
  },
  {
    name: 'CDEK',
    label: 'cdek',
    site: 'cdek.ru',
    logoUrl: 'https://www.cdek.ru/_nuxt/img/4a14227.svg',
    price: 3000.0,
    deliveryTerm: 3,
    calculateUrl: 'https://www.cdek.ru/ru/calculate',
  },
  {
    name: 'DPD',
    label: 'dpd',
    site: 'dpd.ru',
    logoUrl: 'https://www.dpd.ru/template2/newimages/logo.png',
    price: 3000.0,
    deliveryTerm: 3,
    calculateUrl: 'https://www.dpd.ru/ols/calc/calc.do2',
  },
  {
    name: 'GTD',
    label: 'gtd',
    site: 'gtdel.com',
    logoUrl: 'https://ekaterinburg.gtdel.com/images/static/bg/horda/logo.svg',
    price: 2000.0,
    deliveryTerm: 3,
    calculateUrl: 'https://tk-kit.com/order',
  },
  {
    name: 'Байкал Сервис',
    label: 'baikal',
    site: 'baikalsr.ru',
    logoUrl: 'https://www.baikalsr.ru/local/templates/main/i/logo.svg',
    price: 3000.0,
    deliveryTerm: 3,
    calculateUrl: 'https://request.baikalsr.ru/calculator/?guid=31b7cd47-765e-d4cb-47ef-2d04d805b359',
  },
  {
    name: 'Транзит Авто',
    label: 'tranzit-auto',
    site: 'tranzit-auto.ru',
    logoUrl: 'https://30.img.avito.st/640x480/6343126630.jpg',
    price: 3000.0,
    deliveryTerm: 3,
    calculateUrl: 'http://tranzit-auto.ru/raschet-i-oformlenie-perevozki/',
  },

  {
    name: 'Экспресс-Авто',
    label: 'expressauto',
    site: 'expressauto.ru',
    logoUrl: 'https://irecommend.ru/sites/default/files/product-images/157694/1lDN5DDvlriw9kYTibE4MQ.png',
    price: 3000.0,
    deliveryTerm: 1,
    calculateUrl: 'http://expressauto.ru/autokalkulyator',
  },
  {
    name: 'JDE (ЖелДорЭкспедиция)',
    label: 'jde',
    site: 'jde.ru',
    logoUrl: 'https://www.jde.ru/img/header_logo.svg',
    price: 4500.0,
    deliveryTerm: 1,
    calculateUrl: 'https://i.jde.ru/rq/?rnd=63898478',
  },
  {
    name: 'Pony express',
    label: 'pony-express',
    site: 'ponyexpress.ru',
    logoUrl: 'https://www.ponyexpress.ru/local/templates/ponyexpress_main/i/logo.png',
    price: 4500.0,
    deliveryTerm: 1,
    calculateUrl: 'https://www.ponyexpress.ru/support/servisy-samoobsluzhivaniya/tariff/',
  },
  {
    name: 'Почта России',
    label: 'pochta-russia',
    site: 'www.pochta.ru/',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Russian_Post.svg/320px-Russian_Post.svg.png',
    price: 3500.0,
    deliveryTerm: 1,
    calculateUrl: 'https://www.pochta.ru/parcels',
  },
];
